### ISSUE TITLE
Açık kaynak

### ISSUE THREAD

**Issue by bufgix** [tolgaozuygur/gardiyan#1]
Neden açık kaynak değil?

**Comment by tolgaozuygur** [comment]
Cunku cok eski bir platform olan Android Air ile seneler once yazmistim. Kod oldukca daginik ve derlemesi cok zor. Ama yakinda guncel bir platform ile dogru duzgun yazip kaynaklariyla birlikte ekleyecegim. Simdilik deprem olaylari siklastigi icin bu sekilde toparlayip kurulum dosyasini koydum sadece. :)
